# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36f06bbb859ff8b509f84b33aa2837d289a8fd60d0cc709dc00747bc4e0fe5a20cc6160bc96c8476118468308d8463002c82f7ae1e56e4dc6846f913935b5d5d

test:
  secret_key_base: 86ef83908097fa063dbd47880abb1c8959f69d11d9f584a2cb1dcd0045184feb8ca63b90d724112962ea3fa1361192931f6159162e116e5a2e949604eda6eb1f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
